### ISSUE TITLE
Please do a proper release using GitHub release tagging

### ISSUE THREAD

**Issue by DeflateAwning** [FrameworkComputer/Framework-System-Details#3]
Please do the following: 

1. Remove the `.deb` file from the main repo.
2. Add build instructions to build the `.deb` package (in the readme, or in a file called `BUILDING.md`.
3. Add a GitHub release, and upload the `.deb` file there. 

This is standard practice for use of GitHub repos. To best be a part of the open source community, it's important to follow these standards.

**Comment by ctsdownloads** [comment]
Thank you for your feedback, I will look into this when I have the cycles available to do so.

**Comment by DeflateAwning** [comment]
Please re-open this issue until it is completed/fixed.
